user:
  name: 梦奇



spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000

    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit

  sleuth:
    sampler:
      probability: 1

        

management:
  endpoints:
    web:
      exposure:
        include: "*"

        
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/tmp/log

    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka