user:   
  name:  wsw
spring:
  redis:
    host: 192.168.1.129
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0  
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
