user:
  name:  sww
  
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0  
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit    
        
        
 